//#region User data

export const FETCH_USER_REQUEST = 'FETCH_LOGIN_IN_REQUEST';

export const FETCH_USER_REQUEST_WITH_REDIRECT = 'FETCH_USER_REQUEST_WITH_REDIRECT';

export const FETCH_USER_SUCCEEDED = 'FETCH_LOGIN_IN_SUCCEEDED';

export const FETCH_USER_FAILED = 'FETCH_LOGIN_IN_FAILED';

export const LOADING_USER = 'LOADING_LOGIN_IN';

//#endregion