//#region Read Produt Types

export const FETCH_LOAD_PRODUCT_TYPES_TREE_REQUEST = 'FETCH_LOAD_PRODUCT_TYPES_TREE_REQUEST';

export const FETCH_LOAD_PRODUCT_TYPES_TREE_SUCCEEDED = 'FETCH_LOAD_PRODUCT_TYPES_TREE_SUCCEEDED';

export const FETCH_LOAD_PRODUCT_TYPES_TREE_FAILED = 'FETCH_LOAD_PRODUCT_TYPES_TREE_FAILED';

export const LOADING_LOAD_PRODUCT_TYPES_TREE = 'LOADING_LOAD_PRODUCT_TYPES_TREE';

//#endregion