//#region Email check request 

export const FETCH_CHECK_UNIQUE_EMAIL_REQUEST = 'FETCH_CHECK_UNIQUE_EMAIL_REQUEST';

export const FETCH_CHECK_UNIQUE_EMAIL_SUCCEEDED = 'FETCH_CHECK_UNIQUE_EMAIL_SUCCEEDED';

export const FETCH_CHECK_UNIQUE_EMAIL_FAILED = 'FETCH_CHECK_UNIQUE_EMAIL_FAILED';

export const CHECK_UNIQUE_EMAIL_LOGINING = 'CHECK_UNIQUE_EMAIL_LOGINING';

//#endregion


//#region Login logining check request 

export const FETCH_LOGINING_REQUEST = 'FETCH_LOGINING_REQUEST';

export const FETCH_LOGINING_SUCCEEDED = 'FETCH_LOGINING_SUCCEEDED';

export const FETCH_LOGINING_FAILED = 'FETCH_LOGINING_FAILED';

export const LOADING_LOGINING = 'LOADING_LOGINING';


export const FETCH_LOGINING_BACKUP = 'FETCH_LOGINING_BACKUP';
//#endregion


//#region Login in 

export const FETCH_LOGIN_IN_REQUEST = 'FETCH_LOGIN_IN_REQUEST';

export const FETCH_LOGIN_IN_SUCCEEDED = 'FETCH_LOGIN_IN_SUCCEEDED';

export const FETCH_LOGIN_IN_FAILED = 'FETCH_LOGIN_IN_FAILED';

export const LOADING_LOGIN_IN = 'LOADING_LOGIN_IN';

//#endregion

//#region Login out

export const FETCH_LOGIN_OUT_REQUEST = 'FETCH_LOGIN_OUT_REQUEST';

export const FETCH_LOGIN_OUT_SUCCEEDED = 'FETCH_LOGIN_OUT_SUCCEEDED';

export const FETCH_LOGIN_OUT_FAILED = 'FETCH_LOGIN_OUT_FAILED';

export const LOADING_LOGIN_OUT = 'LOADING_LOGIN_OUT';

//#endregion