
//#region Create Produts

export const FETCH_ADD_PRODUCT_REQUEST = 'FETCH_ADD_PRODUCT_REQUEST';

export const FETCH_ADD_PRODUCT_SUCCEEDED = 'FETCH_ADD_PRODUCT_SUCCEEDED';

export const FETCH_ADD_PRODUCT_FAILED = 'FETCH_ADD_PRODUCT_FAILED';

export const LOADING_ADD_PRODUCT = 'LOADING_ADD_PRODUCT';

//#endregion


//#region Read Produts

export const FETCH_LOAD_PRODUCTS_REQUEST = 'FETCH_LOAD_PRODUCTS_REQUEST';

export const FETCH_LOAD_PRODUCTS_SUCCEEDED = 'FETCH_LOAD_PRODUCTS_SUCCEEDED';

export const FETCH_LOAD_PRODUCTS_FAILED = 'FETCH_LOAD_PRODUCTS_FAILED';

export const LOADING_LOAD_PRODUCTS = 'LOADING_LOAD_PRODUCTS';

//#endregion